// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5XQ1sofrWuz2MaNK87u6N5sHyNSsgRtg',
    appId: '1:213377902369:web:21d385956407222640c060',
    messagingSenderId: '213377902369',
    projectId: 'bckducc',
    authDomain: 'bckducc.firebaseapp.com',
    storageBucket: 'bckducc.firebasestorage.app',
    measurementId: 'G-KXR9CDFKKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAknZpHsDqqpyiYmjso3_4hs1OK9KutDiM',
    appId: '1:213377902369:android:a8b54e4a3e402e2b40c060',
    messagingSenderId: '213377902369',
    projectId: 'bckducc',
    storageBucket: 'bckducc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAggN0ogGkz-AdmCFZgn9YgF1as6c1sBCs',
    appId: '1:213377902369:ios:afebd99cc7369ff740c060',
    messagingSenderId: '213377902369',
    projectId: 'bckducc',
    storageBucket: 'bckducc.firebasestorage.app',
    iosBundleId: 'com.example.trainning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAggN0ogGkz-AdmCFZgn9YgF1as6c1sBCs',
    appId: '1:213377902369:ios:afebd99cc7369ff740c060',
    messagingSenderId: '213377902369',
    projectId: 'bckducc',
    storageBucket: 'bckducc.firebasestorage.app',
    iosBundleId: 'com.example.trainning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5XQ1sofrWuz2MaNK87u6N5sHyNSsgRtg',
    appId: '1:213377902369:web:84c827f89eb375f740c060',
    messagingSenderId: '213377902369',
    projectId: 'bckducc',
    authDomain: 'bckducc.firebaseapp.com',
    storageBucket: 'bckducc.firebasestorage.app',
    measurementId: 'G-P5DH5EVWMV',
  );
}
